name: Tests

on:
  - push
  - pull_request

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
      - run: php test.php

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
      - run: php test.php

  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
      - run: php test.php